# Generated by Django 3.1.7 on 2021-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userproductrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductrelation',
            name='advantages',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userproductrelation',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userproductrelation',
            name='disadvantages',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
